name: Main Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      run_pre_jobs:
        description: 'Run pre-jobs before mandatory jobs'
        required: true
        default: false
        type: boolean
      run_post_jobs:
        description: 'Run post-jobs after mandatory jobs'
        required: true
        default: false
        type: boolean

jobs:
  call_reusable_workflow:
    uses: ./.github/workflows/reusable.yml
    with:
      run_pre_jobs: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.run_pre_jobs == true || false }}
      run_post_jobs: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.run_post_jobs == true || false }}
